// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: 'REMOVED',
    messagingSenderId: 'REMOVED',
    projectId: 'REMOVED',
    storageBucket: 'REMOVED.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: 'REMOVED',
    messagingSenderId: 'REMOVED',
    projectId: 'REMOVED',
    authDomain: 'REMOVED.firebaseapp.com',
    storageBucket: 'REMOVED.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: 'REMOVED',
    messagingSenderId: 'REMOVED',
    projectId: 'REMOVED',
    storageBucket: 'REMOVED.firebasestorage.app',
    iosBundleId: 'REMOVED',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: 'REMOVED',
    messagingSenderId: 'REMOVED',
    projectId: 'REMOVED',
    storageBucket: 'REMOVED.firebasestorage.app',
    iosBundleId: 'REMOVED',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: 'REMOVED',
    messagingSenderId: 'REMOVED',
    projectId: 'REMOVED',
    authDomain: 'REMOVED.firebaseapp.com',
    storageBucket: 'REMOVED.firebasestorage.app',
  );
}
