// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC96CbWN0NNuDwWUlykRm3B5zNZDyaCJ6w',
    appId: '1:992326034981:android:073531df9896a61ad201cc',
    messagingSenderId: '992326034981',
    projectId: 'elan-db-55c84',
    storageBucket: 'elan-db-55c84.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2rcKymrl7fyf8NfE5zFtYoTbmnIo5A4A',
    appId: '1:992326034981:web:23581b9425f7d79cd201cc',
    messagingSenderId: '992326034981',
    projectId: 'elan-db-55c84',
    authDomain: 'elan-db-55c84.firebaseapp.com',
    storageBucket: 'elan-db-55c84.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9yRa426N5aodndzlgbfG-Iwj41e9YZ-M',
    appId: '1:992326034981:ios:082535b3e3c86b04d201cc',
    messagingSenderId: '992326034981',
    projectId: 'elan-db-55c84',
    storageBucket: 'elan-db-55c84.firebasestorage.app',
    iosBundleId: 'com.example.elanFlutterproject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9yRa426N5aodndzlgbfG-Iwj41e9YZ-M',
    appId: '1:992326034981:ios:082535b3e3c86b04d201cc',
    messagingSenderId: '992326034981',
    projectId: 'elan-db-55c84',
    storageBucket: 'elan-db-55c84.firebasestorage.app',
    iosBundleId: 'com.example.elanFlutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2rcKymrl7fyf8NfE5zFtYoTbmnIo5A4A',
    appId: '1:992326034981:web:25f9991a983a4a8ed201cc',
    messagingSenderId: '992326034981',
    projectId: 'elan-db-55c84',
    authDomain: 'elan-db-55c84.firebaseapp.com',
    storageBucket: 'elan-db-55c84.firebasestorage.app',
  );
}
